# --- configuring profile spring

# spring:
#   profiles:
#     active: "test"

# ------------------------------


spring:
    profiles:
        active: test
    datasource:
        url: jdbc:postgresql://localhost:5432/logistics_center
        platform: POSTGRESQL
        driver-class-name: org.postgresql.Driver
        username: cit
        password: cit
    jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true