# --- configuring profile spring

spring:
    profiles:
        active: test
    datasource:
        url: jdbc:${database_url}
        platform: ${database_platform}
        driver-class-name: org.postgresql.Driver
        username: ${database_username}
        password: ${database_password}
    jpa:
        hibernate:
          #ddl-auto: create-drop
          ddl-auto: update
        show-sql: true

# --- configuring json doc

jsondoc:
  version: 1.0
  basePath: http://localhost:8080/
  packages: br.com.cit.logistics_center.controllers, br.com.cit.logistics_center.domain.entities, br.com.cit.logistics_center.domain.wrappers