# --- configuring profile spring

spring:
    profiles:
        active: test
    datasource:
        url: jdbc:${database_url}
        platform: ${database_platform}
        driver-class-name: org.postgresql.Driver
        username: ${database_username}
        password: ${database_password}
    jpa:
        hibernate:
          #ddl-auto: create-drop
          ddl-auto: update
        show-sql: true